//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppSiacpiMovil.App.MovilStorage {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="MovilStorage.ISiacpiMensaje")]
    public interface ISiacpiMensaje {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiacpiMensaje/EnviarMensaje", ReplyAction="http://tempuri.org/ISiacpiMensaje/EnviarMensajeResponse")]
        bool EnviarMensaje(string _pTo, string _pMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiacpiMensaje/EnviarMensaje", ReplyAction="http://tempuri.org/ISiacpiMensaje/EnviarMensajeResponse")]
        System.Threading.Tasks.Task<bool> EnviarMensajeAsync(string _pTo, string _pMsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiacpiMensaje/EnviarEmail", ReplyAction="http://tempuri.org/ISiacpiMensaje/EnviarEmailResponse")]
        bool EnviarEmail(string _pEmailTo, string _pNombreTo, string _pNombreFrom, string _pTipoDocumento, string _pAsunto, string _pContenido);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISiacpiMensaje/EnviarEmail", ReplyAction="http://tempuri.org/ISiacpiMensaje/EnviarEmailResponse")]
        System.Threading.Tasks.Task<bool> EnviarEmailAsync(string _pEmailTo, string _pNombreTo, string _pNombreFrom, string _pTipoDocumento, string _pAsunto, string _pContenido);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISiacpiMensajeChannel : AppSiacpiMovil.App.MovilStorage.ISiacpiMensaje, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SiacpiMensajeClient : System.ServiceModel.ClientBase<AppSiacpiMovil.App.MovilStorage.ISiacpiMensaje>, AppSiacpiMovil.App.MovilStorage.ISiacpiMensaje {
        
        public SiacpiMensajeClient() {
        }
        
        public SiacpiMensajeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SiacpiMensajeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiacpiMensajeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SiacpiMensajeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool EnviarMensaje(string _pTo, string _pMsg) {
            return base.Channel.EnviarMensaje(_pTo, _pMsg);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarMensajeAsync(string _pTo, string _pMsg) {
            return base.Channel.EnviarMensajeAsync(_pTo, _pMsg);
        }
        
        public bool EnviarEmail(string _pEmailTo, string _pNombreTo, string _pNombreFrom, string _pTipoDocumento, string _pAsunto, string _pContenido) {
            return base.Channel.EnviarEmail(_pEmailTo, _pNombreTo, _pNombreFrom, _pTipoDocumento, _pAsunto, _pContenido);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarEmailAsync(string _pEmailTo, string _pNombreTo, string _pNombreFrom, string _pTipoDocumento, string _pAsunto, string _pContenido) {
            return base.Channel.EnviarEmailAsync(_pEmailTo, _pNombreTo, _pNombreFrom, _pTipoDocumento, _pAsunto, _pContenido);
        }
    }
}
